### ISSUE TITLE
Crash when Shift Clicking a command

### ISSUE THREAD

**Issue by KidMessiah** [gigabit101/StevesFactoryManager#1]
http://pastebin.com/DYdETHcC

I don't crash when I try to move the command normally, but when I try to use the old shift+click to snap it to the grid I get a crash. 
Just added it to All the Mods version 1.40

**Comment by gigabit101** [comment]
thanks for the report will be fixed in alpha2

**Comment by gigabit101** [comment]
hmm this seems like a mod interaction bug I do not have this issue

**Comment by KidMessiah** [comment]
I updated SFMR to version 1.0.2 and still get this issue? 

http://pastebin.com/P8t3ESZG
I also updated to All the Mods v1.41b

**Comment by jason883** [comment]
@KidMessiah how did you get around this? My game crashes when i shift+right click in any menu in the factory blocks. As well as redstone signals to redstone receivers.

**Comment by gigabit101** [comment]
I can not get this issue

**Comment by jason883** [comment]
[Here](http://pastebin.com/xYJC4pTp) is my crash report. Looks similar to the other guys.

**Comment by KidMessiah** [comment]
@jason883 its an incompatibility with substratum as far as I could tell. I just disabled the mod.
