### ISSUE TITLE
Dupelication bug when using factory manager with AE2 Inscribers. Minecraft 1.10.2

### ISSUE THREAD

**Issue by Crusaderkvw** [gigabit101/StevesFactoryManager#11]
While I was making my normal setup for AE2 Inscriber automation using the factory manager I encountered a rather game breaking bug: the system somehow kept duplicating the resources I put in and the circuits that came out.  

following this guide as always: https://www.youtube.com/watch?v=fY19wYRK7nk  

Specs:
Minecraft version: 1.10.2
Modpack: All The Mods v1.43b
factory "coding" is identical to the vid guide linked above.

Steps to re-produce:
1: make the code
2: input materials(gold in this case)
3: connect the trigger with the chest input code
4: Duplication (profit????)

**Comment by stilesdev** [comment]
I ran into the same issue with automating the AE2 Charger as well.

![Program](https://cloud.githubusercontent.com/assets/1377201/20452740/348e3e02-addf-11e6-9a94-9cad136f77fa.png)

I created the program above, hooked it up to a 1 second timer, and added one Certus Quartz to the Chest. Ended up with this in the chest, continuously adding one Charged Certus Quartz to each slot in the chest every second, without ever removing the item from the Charger.

![Result](https://cloud.githubusercontent.com/assets/1377201/20452745/562ed170-addf-11e6-9177-58edef1088dd.jpg)

**Comment by gigabit101** [comment]
@modmuss50 this seems to be the same as the issue in StevesCarts right?

**Comment by modmuss50** [comment]
Yes, so its got to be you.

**Comment by modmuss50** [comment]
I worked around it, but if other mods have the same issue it needs to be fixed on your end as well.

**Comment by gigabit101** [comment]
yeah I need to sit down and go over that code again... fun times...

**Comment by SilbernerDolch** [comment]
The Dupe can be done much more easily. 
![2016-11-21_20 57 28](https://cloud.githubusercontent.com/assets/19330205/20498393/55f6ca3c-b02d-11e6-97f1-aab64aa462b7.png)

Place the desired block in front of the block gate and SFM will break it and put a copy of it in every chest slot instead of only one in the first free one.
Looks like the "Output" Command is bugged.

**Comment by gigabit101** [comment]
kk that narrows it down big time thanks
