### ISSUE TITLE
Dupe Bug With Block Gate

### ISSUE THREAD

**Issue by UnPure** [gigabit101/StevesFactoryManager#13]
It seems like the dupe problems are still there. https://github.com/gigabit101/StevesFactoryManager/issues/11
Atleast the output dupe bug. https://github.com/gigabit101/StevesFactoryManager/issues/11#issuecomment-262051139

SFM: 1.09
Forge: 12.8.2.2139

If you need any other informations, let me know.

**Comment by gigabit101** [comment]
Well that's odd as I can't get it to happen with the block gate or and project e inventorys any more

**Comment by gigabit101** [comment]
What inventory are you using

**Comment by UnPure** [comment]
I'm just using a normal vanilly chest.
The dupe is happening with (for example) with the block gate breaking Botania Living Wood/Stone.
Just use Input (Block Gate) and Output (Vanilla Chest).

Its also crashing the server if you try to break a Refined Storage Disk Drive with a Block Gate btw.

If you have more questions or need more informations quickly, i'm in #techreborn most of the times as "Backslash".

**Comment by gigabit101** [comment]
Ok so this is a diff bug with just the block gate thanks to the changes in the new Inventory system markDirty is not a thing I can use for now

**Comment by LegendLength** [comment]
I'm also having this problem.  Just a factory manager with a chest and a block breaker.  It seems like the chest content is getting shifted to the right one spot and the new item getting put in.

I also found another duplication issue with a basic storage drawers setup.  When trying to pull to or from the drawer controller things get duplicated.  Not sure if it's the same issue.
