### ISSUE TITLE
Consider integrating stevesaddons functions?

### ISSUE THREAD

**Issue by tgstyle** [gigabit101/StevesFactoryManager#20]
https://github.com/hilburn/StevesAddons

**Comment by gigabit101** [comment]
Some of these will be merged in for 2.X

**Comment by tgstyle** [comment]
Great news!

**Comment by gigabit101** [comment]
One of the first items from Steve's adons is now merged in the 2.X branch

**Comment by mgdgfbhevdyeh** [comment]
@gigabit101 is you busy now?or Did you give up this project?
