### ISSUE TITLE
Crash upon attempting to grid-lock a Command

### ISSUE THREAD

**Issue by Alaric323** [gigabit101/StevesFactoryManager#21]
Greetings,

This crash happens when holding shift and attempting to move one of the command tiles in the Factory Manager.  Using SFM 1.0.9 which is bundled in the All The Mods modpack.

[crash-2016-12-02_21.52.38-client.txt](https://github.com/gigabit101/StevesFactoryManager/files/628661/crash-2016-12-02_21.52.38-client.txt)

**Comment by gigabit101** [comment]
this is a issue only with that pack

**Comment by The-Key** [comment]
The mod that causes this is recipehandler or [NoMoreRecipeConflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict) Here is my full log from using only the latest recommended forge, nomorerecipeconflict, and steve's factory manager: 
[full log.zip](https://github.com/gigabit101/StevesFactoryManager/files/659773/full.log.zip)
