### ISSUE TITLE
[issue] 1.10.2 not reading storage drawers correctly

### ISSUE THREAD

**Issue by winsrp** [gigabit101/StevesFactoryManager#23]
While using storage drawing with a storage controller the items are read very weird, sometimes it read a stack as 1 item, and while moving deposits only 1 unit of the item and takes a stack from the drawer (64 -> 1), and sometimes it reads the stack as a stack but leaves the items in the drawer (infinite extraction from drawer without depletion but starts filling chests like crazy)!

**Comment by winsrp** [comment]
I tested this with the latest version 1.0.11 and is still not working properly it extracts 1 more stack than it should efectively duplicating the last stack it extracts

**Comment by gigabit101** [comment]
Ok will look into this one
