### ISSUE TITLE
Block Duplication (And a lot!) w/ Botania

### ISSUE THREAD

**Issue by cornehoskam** [gigabit101/StevesFactoryManager#24]
I've decided to replicate AkoTheBuilders Botania livingwood and livingrock farm design using SFM, though I came to the realization that there is a very bad duplication bug in the latest version of the mod.

Using just 8 pieces of stone, which Botania turned into livingrock, this is the result.
http://i.imgur.com/32cJlbv.png
(Yes, this was the exact ordering/sorting the mod decided on)

The exact code is as shown in this video:
https://youtu.be/XGscDHRm3YM?t=4m13s

Extra information:
Modpack: Resonant Rise 4 (Not yet released)
Mod version: 1.0.9
Minecraft version: 1.10.2

Thanks.

**Comment by gigabit101** [comment]
Yes this is a known issue I am currently rewriting a load of the Inventory system
