### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by AndreiTS** [gigabit101/StevesFactoryManager#25]
I created a system using steve's and actually aditions to duplicate ores like this: http://i.cubeupload.com/Blq8Sz.png

Then I put 64 gold in the chest, it went to the crusher 
But the chest began to fill with gold
http://i.cubeupload.com/SiFlm0.png

I took the gold but continued: http://i.cubeupload.com/YbFawi.png

**Comment by AndreiTS** [comment]
Update to 1.0.11, Continues to double
I recorded a video showing the bug: https://www.youtube.com/watch?v=tSGkj_RTV1k

**Comment by gigabit101** [comment]
0o I see whats happening easy fix thanks for the vid

**Comment by CJBok** [comment]
when can we expect to have an update on this "easy fix"? As I would really like to use this mod with the inscriber as well.

**Comment by AndreiTS** [comment]
i'm waiting too ;-;

**Comment by gigabit101** [comment]
When I have time I work a full time job aswell I hope to work on this
during the weekend
