### ISSUE TITLE
Issue with Input/Output + StackSizes

### ISSUE THREAD

**Issue by Elvarion** [gigabit101/StevesFactoryManager#26]
- StevesFactoryManager-1.10.2-1.0.11.jar

(Wasnt sure what to name the Title..)

Setting configs to only Allow to pull single item does not work.
Will pull 1-64 depending on size of stack.
Will also keep pulling items despite Output being set to 1.
(In original SFM setting the output would mean that ONLY that amount is allowed in the container.)

Overview of Setup
https://gyazo.com/9cf7efe27a0276e42f5f2174933dad61
Condition is to check IF stone is already in Container

This is how it was used to work in the Original SFM on 1.7.10
https://gyazo.com/381490c15a5b66983fdfac5916badbca

**Comment by Elvarion** [comment]
Similar to #23

**Comment by RobertLSnead** [comment]
I am having a similar issue but with block gates, it ignores the out to 1 and trys to place the whole stack.

**Comment by Elvarion** [comment]
Indeed. Having 2 stacks/items and then doing a check if said item is already in the inventory will pull the first item/stack and then leave the second item/stack alone. But its still not working as it should
