### ISSUE TITLE
[issue][1.10.2] transforming cable camouflage in advanced cable cluster has glitchs

### ISSUE THREAD

**Issue by winsrp** [gigabit101/StevesFactoryManager#30]
Using the transforming cable camouflage in an advanced cable cluster and using the options for bounds makes all kind of weird things. if bounds are to be ignored, you cannot pass, and if you specify a smaller bounding area, the vanilla blocks surrounding the sfm adv cable cluster are not rendered, and  you still cannot pass.

**Comment by Degonsky** [comment]
![2018-03-13_17 46 31](https://user-images.githubusercontent.com/37059920/37352695-8325e35e-26e6-11e8-8de7-e4740f8e2746.png)
Block just pushes away anytime I try to walk in to it. From top you just fall down and get pushed out of the block. And x-ray, ofc

**Comment by gigabit101** [comment]
fixed in 1.12
