### ISSUE TITLE
AE2 Inscriber Bug

### ISSUE THREAD

**Issue by SpacePie** [gigabit101/StevesFactoryManager#38]
I don't know if this is a bug or nerf, but basically the Factory Manager can't put items in the [top or bottom](http://imgur.com/iIldHJK) item slots of the AE2 Inscriber. All items put into the inscriber from the Manager go straight to the middle, no matter what you put the "Target" as. See video [here ](https://youtu.be/6GbpZAmlMZU) for demonstration. Using MC 1.10.2 and mod version 1.0.12.

**Comment by gigabit101** [comment]
fixed in 1.12.1
