### ISSUE TITLE
Creative Supplier isn't recognised by the Inventory Manager

### ISSUE THREAD

**Issue by whizzball1** [gigabit101/StevesFactoryManager#39]
Hello!

I installed SFM recently and wanted to test a build using the Creative Supplier. I wasn't sure how to use it, so I went back to VSWE's videos on the mod and found that the Creative Supplier is attached to the network and shows up as a connected inventory (when using "Input"). However, when I connect the block, I can't find it in "Inventories", either when using "Input" or "Output".

I'm using the latest version of SFM. If you need images, I can provide them.

**Comment by gigabit101** [comment]
yup its not implemented yet

**Comment by luffykick** [comment]
Hi gigabit101, is Santa giving us the creative supplier for Christmas :)?

**Comment by gigabit101** [comment]
removed this for now as i want to make this better
