### ISSUE TITLE
Redstone Receivers are Buggy

### ISSUE THREAD

**Issue by nikkimas** [gigabit101/StevesFactoryManager#40]
Hey,
when I place a redstone receiver, put a block on top of it, put a button on that block, the button gets stuck when it's pressed. 
And every block I place next to the receiver, is not harvestable ( When I break it, it doesn't drop).
It seems like, when the receiver gets an Block Update it break everything around it (attention: I have no clue what I'm talking about. just guessing :D).

SFM Version: StevesFactoryManager-1.10.2-1.0.12
Minecraft: 1.10.2

(All of this could have to do with this Issue: #41 )

**Comment by darman84** [comment]
I'm also experiencing this issue, any time I place redstone near it, when I break it there is no drops for it.

**Comment by Alaric323** [comment]
I can add to this issue.  When placing an EnderIO Redstone Conduit next to a Redstone Receiver, the game crashes, and the world becomes unable to load.

Attached is a crash report.
[crash-2017-01-10_13.10.13-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/696950/crash-2017-01-10_13.10.13-server.txt)

**Comment by Ncrpts** [comment]
I confirm, same issue as Alaric323, also same crash with an rftool timer touching the receiver, also a friend testing said he crashed with vanilla redstone aswell, receivers are very dangerous in their current state, i suggest server owners to blacklist them.

**Comment by gigabit101** [comment]
needs testing in 1.12.1

**Comment by gigabit101** [comment]
should be fixed in 1.12
