### ISSUE TITLE
Crash when joining Server

### ISSUE THREAD

**Issue by nikkimas** [gigabit101/StevesFactoryManager#41]
When I join the Server, I Crash with this report: 
http://pastebin.com/5usYEzQS
After a friend of mine removed the Block I was able to join again.

SFM Version: StevesFactoryManager-1.10.2-1.0.12
Minecraft: 1.10.2

**Comment by lumien231** [comment]
lumien231/Random-Things#184

It looks like you maybe forgot to remove a debug line here?
https://github.com/gigabit101/StevesFactoryManager/blob/1.10.2/src/main/java/vswe/stevesfactory/tiles/TileEntityInput.java#L54

I don't think calling World.getRedstonePower with a null facing is valid.

**Comment by gigabit101** [comment]
Whoops

**Comment by gigabit101** [comment]
fixed in 1.12.1
