### ISSUE TITLE
Item Valve Dupe Bug/Can't Pick Up Cable Cluster Blocks

### ISSUE THREAD

**Issue by DrMeteorite** [gigabit101/StevesFactoryManager#44]
When inputting from an Item Valve or a Rapid Item Valve to any inventory with more than one slot, the item(s) are repeated for each slot. 
[https://imgur.com/a/XZH7E](url)
So, an item input from a valve to a vanilla chest would put 1 of that item in each of the 27 slots, resulting in a total of 27 items.
[https://imgur.com/a/8LFQL](url) 
Furthermore, an array of Item Valves will output 1 item for each valve in each slot. So, an array of 9 valves will output 9 items per slot when given 1 item. A vanilla chest will then receive 153 items when given 1. 
[https://imgur.com/a/u4lwP](url)

Obviously, these are powerful duping glitches and I hope they get resolved soon.

Another issue concerns Cable Cluster and Advanced Cable Cluster Blocks. Simply put, Cluster Blocks placed in the world just break when broken (with the appropriate tool) and do not drop. This is a big issue because Advanced Cable Clusters and compatible components can be quite expensive and misplacing blocks happens to everybody. It seems unbalanced to have such costly consequences.

**Comment by Revvilo** [comment]
Damn, this has been around for that long?
There goes my project of making a frame miner with SFM ;(

**Comment by gigabit101** [comment]
removed for now as I need to do this better
