### ISSUE TITLE
AE2 Interface Multipart Client Crash

### ISSUE THREAD

**Issue by DrMeteorite** [gigabit101/StevesFactoryManager#45]
It would appear that attempting to use SFM to communicate with the Interface Multipart from Applied Energistics 2 causes a client crash. 

![](https://i.imgur.com/qlVrGOf.png)  

- The Interface Block seems to work fine.
- The crash only occurs after a series of commands involving the Interface Multipart is triggered. 
- Crash is instantaneous and definitely repeatable. 
- World is inaccessible after this point. 

EDIT: A crash report would probably help a bit, huh?
[https://paste.ee/p/YPKf5](url)

**Comment by gigabit101** [comment]
fixed in 1.12
