### ISSUE TITLE
Server crash inserting into storage draw with void upgrade

### ISSUE THREAD

**Issue by Saereth** [gigabit101/StevesFactoryManager#46]
Once the storage drawer fills and it starts voiding items steve's crashes he server with a deadlock that has to be mcedited with this log.

https://hastebin.com/yuceqasenu.sql

MC 1.10.2 
StevesFactoryManager-1.10.2-1.0.12	
StorageDrawers-1.10.2-3.7.0

**Comment by gigabit101** [comment]
fixed in 1.12.1
