### ISSUE TITLE
Duplication with Applied

### ISSUE THREAD

**Issue by Gohu29** [gigabit101/StevesFactoryManager#47]
Hello I found a duplication glitch when I use steve's facto for automatise logical press.

Input> Inscriber // target> down
Output>Chest // target> up
Result 
![image](https://cloud.githubusercontent.com/assets/13649609/25072032/bd59f234-22c5-11e7-84b2-dde3b87434ae.png)

Version: StevesFactoryManager-1.10.2-1.0.12

**Comment by WhiskersWatson** [comment]
Can confirm and it also does this from the AE2 stuff advanced inscribers. If you wanted to use this and avoid it duplicating you can set it to output to a specific slot.

**Comment by InjuredWolf** [comment]
Also has similar problems with Blood Magic...

EDIT: In particular the blood altar, from what I've seen so far.

**Comment by Revvilo** [comment]
I can literally just put a block gate pumping into a chest and it immediately adds one of the block that was in front of the block gate to all slots in the inventory.... works with every chest I've tried.
This seems to be a general duplication glitch with a lot of different things.

**Comment by gigabit101** [comment]
fixed in 1.12.1
