### ISSUE TITLE
A Number of Issues

### ISSUE THREAD

**Issue by InjuredWolf** [gigabit101/StevesFactoryManager#48]
Okay. Here goes:

These bugs were found when using a Blood Altar from Blood Magic. I was attempting to automate it using SFM.
Firstly, when it pulls the item out and places it in a chest, it will ALWAYS put the item in a new stack, seemingly.
Secondly, on quick triggers, it seems to put the item INTO the output BEFORE it is removed from the input (that's my guess at least), and consequently proceeds to pull as many of the item as it can in that space of time. 1 Second trigger time seems to be 1 tick or something.

**Comment by InjuredWolf** [comment]
This can be mitigated by restricting the INPUT amount, but not all users will do this.

**Comment by gigabit101** [comment]
fixed in 1.12.1
