### ISSUE TITLE
[FTB BEYOND MC 1.10.2] Adding Steves Factory Manager to my server. (No issue)

### ISSUE THREAD

**Issue by cap1o** [gigabit101/StevesFactoryManager#50]
Hello !

I just would ask if i can add to my FTB Beyond v1.10 safely the mod Steve's Factory Manager with out troubles with other mod or mess up my game ? 
Of course i will back up my world if troubles but i prefer ask before try it.
I'm running the modpack on private server on MC 1.10.2.

Thank you !

**Comment by MichaelHillcox** [comment]
From my experience you will experience bugs... A lot of bugs. This mod is only just running let alone being stable. There was a lot of changes between 1.7.10 and 1.10.2. You are welcome to give it a go but just remember that it's basically in `alpha` and at this time looking like the development is going very slowly.
