### ISSUE TITLE
Can't create anything in the Manager block [1.12.1] 

### ISSUE THREAD

**Issue by Learwin** [gigabit101/StevesFactoryManager#51]
When I place down the Manager block and open it, then I can't create any inputs, triggers or any other button in the GUI. I can open the user preferences though.
Forge: 2063 for 1.12.1
Mod Version: StevesFactoryManager-1.12.1-1.0.12

**Comment by gigabit101** [comment]
yes this is already fixed in dev (Packet Issue)
