### ISSUE TITLE
[1.10.2] Trash Can = Crash Can

### ISSUE THREAD

**Issue by ThexXTURBOXx** [gigabit101/StevesFactoryManager#53]
Sorry for that title xD
Well, if you set the Trash Can from Extra Utilities as a Output, then the game crashes when the mod tries to move a item into it.
Crash log: https://pastebin.com/Bj1MsL3M

**Comment by MichaelHillcox** [comment]
Best title I've seen in a long time :D

**Comment by ThexXTURBOXx** [comment]
xD

**Comment by gigabit101** [comment]
fixed in 1.12

**Comment by Naheulf** [comment]
Same as #43
