### ISSUE TITLE
Game Crashes when using ore dictionairy

### ISSUE THREAD

**Issue by Jayceena** [gigabit101/StevesFactoryManager#6]
I was trying to sort logs and changed it from fuzzy to ore dict so I could get both types of logs sorted and it crashed.
[crash-2016-11-11_16.22.54-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/586790/crash-2016-11-11_16.22.54-server.txt)

**Comment by Jayceena** [comment]
Suggestion: make a config option that you can have disable all triggers so if this happens you can use the config to stop the crashing.

**Comment by gigabit101** [comment]
Thanks for the report
