### ISSUE TITLE
[1.10.2-1.0.13] Target side is not used with vanilla furnace and all SidedInventory

### ISSUE THREAD

**Issue by Naheulf** [gigabit101/StevesFactoryManager#60]
If we select only one side as target with furnace all slots are selected.

Suspected cause: For steve factory furnace doesn't apear as SidedInventory.

**Comment by Naheulf** [comment]
This bug was added with new [capabilities system](http://mcforge.readthedocs.io/en/latest/datastorage/capabilities/). It change how to access side slots in inventory and broke lot of code...

**Comment by loordgek** [comment]
https://gist.github.com/loordgek/3b93d469bc941ee6581390bcaa3fe218
does this help you ???????

**Comment by Naheulf** [comment]
For the moment I do not have time to work on Steve Factory Manager. But I think it could help, thanks.

**Comment by gigabit101** [comment]
I am currently away from home so I can not do much atm

**Comment by gigabit101** [comment]
Fixed in 1.12.2
