### ISSUE TITLE
[1.10.2-1.0.13] Others dupe bugs

### ISSUE THREAD

**Issue by Naheulf** [gigabit101/StevesFactoryManager#61]
On my server we found two duplicate bugs.

1. Multibloc duplicate bug
Logic with many output (EnderIO) blocs can duplicate items. (I search a simpler setup that also make the bug)

2. Nested inventory duplicate bug
With RFTool's modular storage. Input all storage module slots and output to simple chest will duplicate the first storage module internal slot and void others slots. I don't know if it's undertandable.

**Comment by gigabit101** [comment]
Fixed in 1.12.2

**Comment by Naheulf** [comment]
Where is 1.12.2 jar file ?
