### ISSUE TITLE
[1.10.2-1.0.13] Pulling from Storage Drawers Crashes

### ISSUE THREAD

**Issue by HotaruBlaze** [gigabit101/StevesFactoryManager#63]
**Issue**
Pulling items from storage drawers and moving them into another inventory crashes 

 **Note**
Both are blank blacklist, Crashing occurs when the drawer is emptied, SFM continues to pull.

**Versions**
- Minecraft 1.10.2
- Chameleon-1.10.2-2.3.0.jar
- compatlayer-1.10-0.2.9.jar
- RebornCore-1.10.2-2.13.6.142-universal.jar
- StevesFactoryManager-1.10.2-1.0.13.jar
- StorageDrawers-1.10.2-3.7.10.jar

### Repeatable ###
 **Crash Log**
https://pastebin.com/NcqKCZKr

 **Layout**
![SFM](https://img.fluttershub.xyz/flutters/nqz7c4jdx.png)

 **SFM Setup**
![SFM](https://img.fluttershub.xyz/flutters/cw6wm7d46.png)

**Comment by gigabit101** [comment]
Fixed in 1.12.2
