### ISSUE TITLE
[Issue] [1.10.2] Redstone updates "corruption"

### ISSUE THREAD

**Issue by Degonsky** [gigabit101/StevesFactoryManager#65]
After placing in the world redstone reciever, bugs start to apper, mostly they connected with any of the redstone-connected blocks. In creative placed redstone-connected items sometimes get consumed (espetially if placed near redstone reciever); redsone start to glitch and don't render properly. Game sometime crashes,when redstone reciever get signal.

Playing with other mods, and because of that found the problem. Some blocks from other mods rely on block updates (scanner, "Extra Utilities 2"), and that seems to cause a big problem with redstone reciever - game immedeatly crashes and won't load again because "not enough memory"

![2018-03-13_17 35 59](https://user-images.githubusercontent.com/37059920/37352302-a5490ef8-26e5-11e8-9319-a14ad2bce55e.png)
[crash-2018-03-13_15.48.26-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807597/crash-2018-03-13_15.48.26-server.txt)
[crash-2018-03-13_15.55.09-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807598/crash-2018-03-13_15.55.09-server.txt)
[crash-2018-03-13_16.04.10-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807599/crash-2018-03-13_16.04.10-server.txt)
[crash-2018-03-13_16.07.44-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807600/crash-2018-03-13_16.07.44-server.txt)
[crash-2018-03-13_16.13.22-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807601/crash-2018-03-13_16.13.22-server.txt)
[crash-2018-03-13_17.22.34-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807602/crash-2018-03-13_17.22.34-server.txt)
[crash-2018-03-13_17.33.45-server.txt](https://github.com/gigabit101/StevesFactoryManager/files/1807603/crash-2018-03-13_17.33.45-server.txt)

**Comment by gigabit101** [comment]
fixed in 1.12
