### ISSUE TITLE
Where is the mod at right now?

### ISSUE THREAD

**Issue by Arudarin** [gigabit101/StevesFactoryManager#68]
About how complete is the mod? What is as of right now, not working?

**Comment by MichaelHillcox** [comment]
3 commits in the past 3 months. From what I understand @gigabit101 is a very busy man and this project is a side project for him so I'd say that this project is going to take a long time to see a fully stable release. Although, from what I've seen, progress has been made in the previous months.

**Comment by gigabit101** [comment]
I am still working on it from time to time, I also have other projects to maintain as well as a job.
I have done some more work that is yet to be pushed to github as it requires some testing.

I hope to have a beta out soon but it will be missing some features. Soon(tm)

**Comment by Furious1964** [comment]
So you recommend another block that can duplicate the function of the Item Valve? I really need that item ATM.

**Comment by Naheulf** [comment]
Can you send last compilable version on curse as alpha version ?

**Comment by MichaelHillcox** [comment]
@Furious1964 Item Ducts from TE, Pipes from Extra Utils, Plently of others, What do you need from it specifically?

**Comment by Furious1964** [comment]
It was to put crystal seeds from AE2 into a pool of water and take out fully grown ones. I was able to solve that problem with a transfer node.

**Comment by MichaelHillcox** [comment]
Use an item dropper with a vacume hopper? or a vacume hopper alternative, There is a few of them. I know AE2 has an item that can pick items up with a whitelist so that would work.

**Comment by Arudarin** [comment]
@Naheulf , @gigabit101 does not have the rights to share a compiled version of the mod.

**Comment by gigabit101** [comment]
Wrong I do so... But currently I am away for 6 more weeks for work so no
updates any time soon

**Comment by MichaelHillcox** [comment]
@gigabit101 If you're able to push your latest changes to an unstable 2.0 branch or something like that and make an issue with a few tasks that need doing, I'd happy take a look at it and see how much I can help out where needed.

**Comment by Arudarin** [comment]
@gigabit101 you may want to change the Readme then...
