### ISSUE TITLE
[Question] Porting status

### ISSUE THREAD

**Issue by hnOsmium0001** [gigabit101/StevesFactoryManager#70]
What is the current plan for porting to 1.13? It seems like works are don't on `2.0.X`, which is 1.12.2. I would happy to contribute for porting to either version.

**Comment by gigabit101** [comment]
At the moment I have no plans to continue working on this without some help, If you wish to contribute feel free to submit PR's and if you do I can sort out access to the repo.

Currently, I am employed full time and do not have the time required to keep this mod going on my own

**Comment by MichaelHillcox** [comment]
If I find some time I may put some work in to help out but I'm in the same position as you really. I would still love to see this mod live once more 👍
