### ISSUE TITLE
Server boot crash

### ISSUE THREAD

**Issue by Gbergz** [gigabit101/StevesFactoryManager#81]
I think this might've already been reported, but it doesn't hurt to report it again if so.
Server crashes when trying to boot it with this mod installed.

### Mod Version:
- 3.0.0-a7

### MC Version:
- 1.14.4

### Forge Version:
- 28.1.1

# What happens:
- Trying to start my server with the mod installed makes it crash after just 10 seconds or so. ~

# Crash Report:
( I don't know if its technically a crash report for this mod but it's the only one that shows up when server does crash.)
[https://pastebin.com/0bgJLB2C](https://pastebin.com/0bgJLB2C)

**Comment by hnOsmium0001** [comment]
I suspect this is because I'm still building with the beta Forge version, but in production most people use the release. I uploaded another build that uses Forge 1.14.4-28.1.1, that might help.
Please tell me if this bug still persists after updating.

**Comment by hnOsmium0001** [comment]
@Gbergz Can you give me an update on this? If it still occurs, a full log (debug) would be very helpful)

**Comment by Electrofried** [comment]
[debug.log](https://github.com/gigabit101/StevesFactoryManager/files/3679723/debug.log)
here is my crashlog, 
vswe.stevesfactory.logic.procedure.IntervalTriggerProcedure.<init>(INetworkController)void/newInvokeSpecial
Would be great if we could get this working on servers

**Comment by hnOsmium0001** [comment]
This should be fixed in `alpha15`.
