### ISSUE TITLE
Sidedness issue with dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [gigabit101/StevesFactoryManager#82]
Don't worry 90% of the mods have had issues with dedicated server sidedness because it changed in 1.14

Log excerpt-
```
Failed to create mod instance. ModID: sfm, class vswe.stevesfactory.StevesFactoryManager
java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
```

stacktrace -
https://gist.github.com/ProsperCraft/a02a0dc478058873c4b10ad5d1c34271

Full log-
https://gist.github.com/ProsperCraft/d80932b4c86c86e4ed183febfc73ed0c

StevesFactoryManager-1.14.4-3.0.0-alpha8
forge-1.14.4-28.1.1

Useless crashlog-
https://gist.github.com/ProsperCraft/4f26e2b1e99f1ca55705419b6058ff2a

**Comment by gigabit101** [comment]
#Fail @hnOsmium0001 ;)

**Comment by hnOsmium0001** [comment]
Hopefully this is fixed in build `alpha9`
