### ISSUE TITLE
Crash when using gui button

### ISSUE THREAD

**Issue by Austin5003** [gigabit101/StevesFactoryManager#85]
Occurred in 3.0.0 alpha 13, I just opened the manager gui and pressed the create trigger button
[crash-2019-09-23_21.12.01-client.txt](https://github.com/gigabit101/StevesFactoryManager/files/3644765/crash-2019-09-23_21.12.01-client.txt)

**Comment by hnOsmium0001** [comment]
Yes that is a known problem, I will release a new build in today (hopefully) that fixes this problem.
Thanks for reporting!

**Comment by hnOsmium0001** [comment]
Fixed in `alpha14`
