### ISSUE TITLE
Crash after placing Factory Manager

### ISSUE THREAD

**Issue by NielsPilgaard** [gigabit101/StevesFactoryManager#89]
One of my players reported a server crash, that happened right after a player placed a Factory Manager.

https://pastebin.com/VzSKUEqN

StevesFactoryManager-1.14.4-3.0.0-alpha17
Forge-1.14.4.28.1.56

**Comment by PessimisticBastard** [comment]
Same issue. The moment I created an event in the factory manager, it threw the same error.

**Comment by hnOsmium0001** [comment]
Sorry that I didn't see this. Somehow Github didn't send me any notification.
This should be fixed in `alpha20` which I just posted today.
