### ISSUE TITLE
Sidedness appears to be broken

### ISSUE THREAD

**Issue by Heufneutje** [gigabit101/StevesFactoryManager#9]
I'm telling my inventory manager to move coal from a chest into a vanilla furnace on the top side (I have Extreme Reactors installed so it should be allowed in the top slot to make graphite), yet it always inserts it into the bottom of the furnace no matter what side I choose. I'm having the same issue with Applied Energistics 2 Inscribers.

My versions to reproduce:
Forge 12.18.2.2125
Steve's Factory Manager 1.0.6
Applied Energistics 2 rv4-alpha-5
Extreme Reactors 0.4.5.19

**Comment by gigabit101** [comment]
This is a problem with the new capabilities system...

**Comment by kurokuno** [comment]
hmm i get the reason for the change but at the same time the inability to automate many sided things is rather frustrating it makes using this far less useful

**Comment by gigabit101** [comment]
It will return there is a sided inventory capability but I have yet to add
the support for it

**Comment by gigabit101** [comment]
Not only that there will be a per slot option soon so insert only to slot 1
and so on

**Comment by kurokuno** [comment]
awesome gig =D good news to have coming

**Comment by gigabit101** [comment]
Yeah as you can imagine how much the mod dose with inventorys it's not a
easy change to make
