### ISSUE TITLE
dupe bug with feedback loop

### ISSUE THREAD

**Issue by yyttuuyy** [gigabit101/StevesFactoryManager#94]
Version 1.14.4
ATM4 (addition of omega craft)
used a wooden barrel with a ore doubling setup if barrel is inserted into on two sides it gave stacks of the ore it inserted(did not have as much before created 27 stacks before realizing filling barrel)

**Comment by hnOsmium0001** [comment]
This is temporarily fixed by adding a condition such that each inventory can only be scanned once. However this solution will still break if multiple input commands were used, so I have to come up with something better later.

**Comment by hnOsmium0001** [comment]
Should be fixed in `alpha24`
