### ISSUE TITLE
Item duping 1.14.4

### ISSUE THREAD

**Issue by Wlnfr** [gigabit101/StevesFactoryManager#96]
Minecraft Version: 1.14.4

Forge Version: 1.14.4-forge-28.2.3

Mod Version: 
Cyclic-1.14.4-0.1.3
StevesFactoryManager-1.14.4-3.0.0-alpha26

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Found in ATM4 modpack, tested in new instance with only Steves Factory Manager and Cyclic mods.
Using factory manager to transfer items from item collector to another inventory(whitelisted) dupes any non-whitelisted item that stays in item collector in any 2 slots with at least one same item in different slots.
I've posted the exact same issue on Cyclic github as I'm not sure which mod's fault it is. Feel free to close the issue if it's not caused by your mod.

Video/images/gifs (direct upload or link): 
https://drive.google.com/open?id=1NNqFLD1ckFtrsksH52lPFE0L-4i3avuu

Counterpart: Lothrazar/Cyclic#1349

**Comment by hnOsmium0001** [comment]
This is partially (I might have read something wrong) determined as a buf from Forge. A PR has been submitted. MinecraftForge/MinecraftForge#6580

Meanwhile this hotfix build should work
https://www.curseforge.com/minecraft/mc-mods/steves-factory-manager-reborn/files/2909298

**Comment by Wlnfr** [comment]
Thanks for the quick reply and hotfix. I will wait for the new forge update.

**Comment by hnOsmium0001** [comment]
Since the 1.14.4 version is EOL, even with Forge not fixing this bug in 1.14, I'll close this issue.
(It is fixed at the root in 1.15)
